-- A FUNÇÃO UPPER COLOCA TODOS OS CARACTERES EM CAIXA ALTA(MAIUSCULO).

SELECT 
  UPPER("[COLUNA COM TEXTO]")
FROM
  ["Sua Tabela"]
-- ESSA CONSULTA IRÁ MOSTRAR TODOS TODOS OS CARACTERES DA COLUNA QUE VOCÊ ESCOLHEU EM CAIXA ALTA, RECOMENDO QUE USE COMO EXEMPLO COLUNA DE NOMES DE USUÁRIO
  

--EXEMPLO COM WHERE

SELECT 
  "NOME"
FROM 
  ["SUA TABELA"]
WHERE
  NOME = UPPER(NOME)

--MOSTRARÁ APENAS OS NOMES NA TABELA QUE ESTÃO EM CAIXA ALTA
